server:
  port: 1241
#启动模式
spring:
  profiles:
    active: dev
  #banner
  banner:
    location: classpath:/banner/banner.txt
  # swagger 集成 高版本springboot   策略变化设置
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  servlet:
    # 文件上次大小限制设置
    multipart:
      # 单个文件最大大小
      max-file-size: 2048MB
      # 整个请求大小限制
      max-request-size: 2048MB


jasypt:
  encryptor:
    algorithm: PBEWITHHMACSHA512ANDAES_256
    key-obtention-iterations: 1000
    pool-size: 1
    salt-generator-classname: org.jasypt.salt.RandomSaltGenerator
    iv-generator-classname: org.jasypt.iv.RandomIvGenerator
    string-output-type: base64
    # password就是盐值
    #password: start input


mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# springdoc
springdoc:
  swagger-ui:
    tags-sorter: alpha
  api-docs:
    path: /v3/api-docs
  default-flat-param-object: true
knife4j:
  enable: true
  setting:
    language: zh_cn
    swagger-model-name: 实体类列表