server:
  port: 9088

# 学习框架 就应该把 log打开 不知道出错了 完全不知道啥原因
logging:
  level:
    org:
      springframework:
        security: trace

mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml

spring:
  datasource:
    url: jdbc:mysql://yiruserene.top:3306/sandwich?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: ENC(jelC1fjDfZ5PG7c8uG/0iRjx/HGJgbHI1A4CtgFF09TPiBe+YyflAxb+hVHY/SOm)
    password: ENC(p5067+1TCj3uIYyTXp5unyyitXAI0q1h5IhxNWNcc0SdiMLm9Xik1ZwtcOPYG78l)


#请求密码模式的token用的 和spring oauth自己的配置没什么关系
oauth2:
  token-url: "http://127.0.0.1:9088/oauth2/token"


# 作为resources服务器用的配置
  security:
    oauth2:
      resourceserver:
        jwt:
          # 如果 带着token认证 总是显示不合法 可能是这里配置ip的问题
          # Jwt中claims的iss属性，也就是jwt的签发地址，即认证服务器的根路径   验证token的真实性
          # 资源服务器会进一步的配置，通过该地址获取公钥以解析jwt
          issuer-uri: http://127.0.0.1:9088
