server:
  port: 8082

logging:
  level:
    org:
      springframework:
        security: trace


spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          # Jwt中claims的iss属性，也就是jwt的签发地址，即认证服务器的根路径
          # 资源服务器会进一步的配置，通过该地址获取公钥以解析jwt
          issuer-uri: http://oauth.local.server:9000
