server:
  port: 9088
#  ssl:
#    enabled: true
#    key-store-type: JKS                     # 改为 JKS
#    #   key-store: classpath:server.jks         # 如果文件在 resources 目录下
#    key-store: file:D:/certs/192_168_66_102/server.jks   # 如果使用绝对路径
#    key-store-password: "123456"            # JKS 文件的密码
#    key-alias: myapp                        # 必须与 JKS 中的别名一致
#  http2:
#    enabled: true

# 学习框架 就应该把 log打开 不知道出错了 完全不知道啥原因
logging:
  level:
    org:
      springframework:
        security: trace

mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml

spring:
  datasource:
    url: jdbc:mysql://49.235.149.110:3306/sandwich?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: ENC(jelC1fjDfZ5PG7c8uG/0iRjx/HGJgbHI1A4CtgFF09TPiBe+YyflAxb+hVHY/SOm)
    password: ENC(p5067+1TCj3uIYyTXp5unyyitXAI0q1h5IhxNWNcc0SdiMLm9Xik1ZwtcOPYG78l)
  data:
    redis:
      host: 49.235.149.110
      port: 6379
      password: ENC(uJjGYgAuROdH+xJKEyeznHV8RL2zz1I/58iwtDQ8KlPHMuW4qNRkNHFaw0m2EnRE)
      jedis:
        pool:
          max-idle: 500
          min-idle: 50
          max-active: 2000
          max-wait: 1000
      timeout: 5000

#忽略token认证
security:
  permit:
    urls:
      - /api/user-center/user/login
      - /api/user-center/user/register
      - /api/user-center/user/slider/generate
      - /api/user-center/user/slider/verify
      - /api/user-center/user/qrCode/**

#请求密码模式的token用的 和spring oauth自己的配置没什么关系
oauth2:
  token-url: "http://127.0.0.1:9088/oauth2/token"


